pipeline {
    agent any

    environment {
        IMAGE_NAME = "coursedatas:1.0"
        KUBECONFIG_FILE = credentials('kubeconfig')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Varaprasad-22/cicdpipeline.git'
            }
        }

        stage('Build JAR') {
            steps {
                dir('coursedatas') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Enable Minikube Docker Engine') {
            steps {
                bat """
                    for /f "tokens=* usebackq" %%x in (`minikube -p minikube docker-env --shell cmd`) do %%x
                """
            }
        }

        stage('Build Docker Image in Minikube') {
            steps {
                dir('coursedatas') {
                    bat """
                        docker build -t coursedatas:1.0 .
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                writeFile file: 'kubeconfig', text: KUBECONFIG_FILE
                bat """
                    set KUBECONFIG=kubeconfig
                    kubectl apply -f coursedatas/mysql.yaml
                    kubectl apply -f coursedatas/coursedatas.yaml
                """
            }
        }
    }

    post {
        success {
            echo "Deployment SUCCESS!"
        }
        failure {
            echo "Deployment FAILED!"
        }
    }
}
